function h = patchPoly(V, fc, fa, ec, lw, ls)
    h = [];
    if isempty(V) || size(V,1) < 3
        return
    end
    h = patch('Vertices', V, ...
              'Faces', 1:size(V,1), ...
              'FaceColor', fc, ...
              'FaceAlpha', fa, ...
              'EdgeColor', ec, ...
              'LineWidth', lw, ...
              'LineStyle', ls);
end